### ISSUE TITLE
TypeError: Cannot read property 'save' of undefined

### ISSUE THREAD

**Issue by GlenCarlierBackup** [iddogino/mongoTriggers#1]
Hi,

When trying to use this:

```
triggers(db.users).update(function() {
    console.log("Database Updated");
});
```

I keep getting this error:

```
D:\Projects\Easybike\node_modules\mongo-triggers\index.js:101
    collection.save = injectTriggers(collection.save, triggers.save, listeners
                                               ^
TypeError: Cannot read property 'save' of undefined
    at module.exports (D:\Projects\Easybike\node_modules\mongo-triggers\index.js:101:48)
    at Object.<anonymous> (D:\Projects\Easybike\server.js:37:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Am I doing something wrong/what could be the problem?

**Comment by iddogino** [comment]
This is because db.users does not exist - and thus undefined. Can you try doing triggers(db.collection('users')).update(function() {
    console.log("Database Updated");
});
